export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const MANAGER_ROUTE = '/manager'
export const SUPPLIER_ROUTE = '/supplier'
export const ADMIN_ROUTE = '/admin'